import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateTaxReportPDF = (report: any, transactions: any[], user: any) => {
  const doc = new jsPDF();
  
  // Brand Colors
  const primaryColor: [number, number, number] = [99, 102, 241]; // brand-purple roughly
  const darkColor: [number, number, number] = [15, 23, 42]; // brand-dark

  // Header
  doc.setFontSize(24);
  doc.setTextColor(...darkColor);
  doc.text('RestoreChain', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Official Tax Documentation - Form 8949 (Substitute)', 14, 30);
  
  // Line separator
  doc.setDrawColor(226, 232, 240); // gray-200
  doc.setLineWidth(0.5);
  doc.line(14, 35, 196, 35);
  
  // User Info
  doc.setFontSize(12);
  doc.setTextColor(...darkColor);
  doc.text('Taxpayer Information', 14, 45);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Email: ${user?.email || 'N/A'}`, 14, 52);
  doc.text(`Account ID: ${user?.id || 'N/A'}`, 14, 58);
  doc.text(`Tax Year: ${report.tax_year}`, 14, 64);
  doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 14, 70);

  // Summary
  const txCount = transactions.length || 0;
  doc.setFontSize(12);
  doc.setTextColor(...darkColor);
  doc.text('Transaction Summary', 14, 85);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Total Transactions Processed: ${txCount}`, 14, 92);
  
  // Transactions Table
  const tableData = transactions.map(tx => [
    new Date(tx.created_at).toLocaleDateString(),
    (tx.type || '').toUpperCase(),
    tx.asset || 'N/A',
    tx.amount || '0',
    tx.status || 'completed'
  ]);

  autoTable(doc, {
    startY: 100,
    head: [['Date', 'Type', 'Asset', 'Amount', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: primaryColor, textColor: 255 },
    styles: { fontSize: 9, cellPadding: 3 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      'This document is generated by RestoreChain for informational purposes. Consult a tax professional.',
      14,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  const filename = `RestoreChain_TaxReport_${report.tax_year}.pdf`;
  doc.save(filename);
};
