const fs = require('fs');
let content = fs.readFileSync('src/lib/pdfExport.ts', 'utf8');
content = content.replace(
  "'This document is generated by Tracefield for informational purposes. Consult a tax professional.',",
  "'Tracefield Ltd. | London, UK | info@tracefield.co.uk | This document is generated for informational purposes. Consult a tax professional.',"
);
fs.writeFileSync('src/lib/pdfExport.ts', content);
